config/routes.rb
Hacker::Application.routes.draw do
  resources :comments

  devise_for :users

  root to: "links#index"

  resources :links
  resources :votes
  resources :users
  match '/links/:link_id/comments' => 'comments#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :link
  attr_accessible :body, :user_id, :link_id

  validates_presence_of :body
end

app/models/link.rb
class Link < ActiveRecord::Base
  belongs_to :user
  has_many :votes
  has_many :comments

  attr_accessible :description, :url, :user_id, :rating

  validates :description, :url, :presence => true
  validates_uniqueness_of :url

  scope :rating_sort, order('rating DESC')
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  attr_accessible :email, :password, :password_confirmation, :remember_me, :username

  has_many :links
  has_many :votes
  has_many :comments

  validates :username, :presence => true
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :link

  validates :user, :link, :presence => true

  attr_accessible :link_id, :user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  # GET /comments
  # GET /comments.json
  before_filter :check_for_id, :only => [:index, :new]

  def index
    @link = Link.find(params[:link_id])
    @comments = Comment.where(:link_id => @link.id)

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @comments }
    end
  end

  # GET /comments/new
  # GET /comments/new.json
  def new
    @comment = Comment.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @comment }
    end
  end

  # POST /comments
  # POST /comments.json
  def create
    @comment = Comment.new(params[:comment])

    respond_to do |format|
      if @comment.save
        format.html { redirect_to "/links/#{@comment.link.id}/comments", notice: 'Comment was successfully created.' }
        format.json { render json: comments_path, status: :created, location: @comment }
      else
        format.html { render action: "new" }
        format.json { render json: @comment.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def check_for_id
    if params[:link_id].blank?
      redirect_to root_path
    end
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = LinkDecorator.all.sort_by { |l| l.votes.size.to_i }.reverse
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(params[:link])

    if @link.save
      redirect_to links_path, notice: 'Link was successfully created.'
    else
      render action: "new"
    end
  end
end

app/controllers/votes_controller.rb
class VotesController < ApplicationController
  before_filter :authenticate_user!

  def create
    if request.xhr?
      link = Link.find(params[:link_id])
  
      if current_user.votes.where(:link_id => params[:link_id]).count == 0
        @vote = current_user.votes.create(link_id: params[:link_id])
        response = { "new_count" => link.votes.count, "has_voted" => false }
      else
        response = { "new_count" => 0, "has_voted" => true }
      end
      
      render :json => response.to_json
    else
      render :text => "Nope."
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/links_helper.rb
module LinksHelper
  def devise_link(signed_in)
    if signed_in
      link_to 'Sign Out', destroy_user_session_path, method: 'delete', :class => 'btn btn-mini', :id => 'logout'
    else
      link_to 'Sign In', new_user_session_path, method: 'get', :class => 'btn btn-mini', :id => 'logout'
    end
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/votes_helper.rb
module VotesHelper
end

app/views/comments/_form.html.erb
<%= form_for @comment, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :body, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_area :body, :class => 'text_area' %>
    </div>
  </div>

  <%= f.hidden_field :link_id, :value => params[:link_id] %>
  <%= f.hidden_field :user_id, :value => current_user.id %>


  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                comments_path, :class => 'btn' %>
  </div>
<% end %>

app/views/comments/edit.html.erb
<%- model_class = @comment.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/comments/index.html.erb
<%- model_class = Comment.new.class -%>
<h1><%= link_to @link.description, @link.url %></h1>
<p class="link_details">
  <strong><%= @link.user.email %></strong> submitted on
  <strong><%= Date.parse(l @link.created_at).strftime('%m/%d/%Y') %></strong>
</p>
<table class="table table-striped">
  <tbody>
    <% @comments.each do |comment| %>
      <tr>
        <td>
          <p>
            <strong><%= comment.user.username %></strong> wrote on
            <strong><%= Date.parse(l @link.created_at).strftime('%m/%d/%Y') %></strong>
          </p>
          <p><%= comment.body %></p>
        <td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to t('.new', :default => t("helpers.links.new")), new_comment_path(:link_id => params[:link_id]), :class => 'btn btn-primary' if user_signed_in? %>
<%= link_to "Back to Links", '/', :class => 'btn btn-primary' %>

app/views/comments/new.html.erb
<%- model_class = @comment.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/comments/show.html.erb
<%- model_class = @comment.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<p>
  <strong><%= model_class.human_attribute_name(:user_id) %>:</strong><br>
  <%= @comment.user_id %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:link_id) %>:</strong><br>
  <%= @comment.link_id %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:body) %>:</strong><br>
  <%= @comment.body %>
</p>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              comments_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_comment_path(@comment), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              comment_path(@comment),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Hacker</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <h3 id="app_title">Super Awesome Hacker Links</h3>

<%= yield %>

</body>
</html>

app/views/links/_form.html.erb
<%= form_for @link, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :url, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :url, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>

  <%= f.hidden_field :user_id, :value => current_user.id %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                links_path, :class => 'btn' %> 
  </div>
<% end %>

app/views/links/edit.html.erb
<%- model_class = @link.class -%>
<h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                 :default => "Edit #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/links/index.html.erb
<%= devise_link(user_signed_in?) %>

<%- model_class = Link.new.class -%>

<%- flash.each do |key, msg| -%>
  <div id="<%= key %>">
    <p><%= msg %></p>
  </div>
<%- end -%>

<% if @links.count > 0 %>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Rate</th>
      <th>Link</th>
      <th>Votes</th>
      <th>Comments</th>
      <th>Submitted By</th>
      <th>Submitted On</th>
    </tr>
  </thead>
  <tbody>
      <% @links.each do |link| %>
        <tr>
          <td><%= link.vote_button(link, current_user, user_signed_in?) %></td>
          <td><%= link_to link.description, link.url %></td>
          <td class="vote_count">+<%= link.votes.size %></td>
          <td><%= link_to "#{link.comments.size} | view", "/links/#{link.id}/comments", :class => 'btn btn-mini' %> </td>
          <td><%= link.user.username %></td>
          <td><%= Date.parse(l link.created_at).strftime('%m/%d/%Y') %></td>
        </tr>
      <% end %>
  </tbody>
</table>

<% else %>
  <p class="no_links">No links submitted. :(</p>
<% end %>

<%= link_to "Submit Awesome Shit", new_link_path, :class => 'btn btn-primary' if user_signed_in? %>

app/views/links/new.html.erb
<%- model_class = @link.class -%>
<h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                               :default => "New #{model_class.model_name.human}") %></h1>
<%= render :partial => 'form' %>

app/views/links/show.html.erb
<%- model_class = @link.class -%>
<h1><%=t '.title', :default => model_class.model_name.human %></h1>

<p>
  <strong><%= model_class.human_attribute_name(:url) %>:</strong><br>
  <%= @link.url %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:user_id) %>:</strong><br>
  <%= @link.user_id %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:description) %>:</strong><br>
  <%= @link.description %>
</p>
<p>
  <strong><%= model_class.human_attribute_name(:rating) %>:</strong><br>
  <%= @link.rating %>
</p>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              links_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_link_path(@link), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              link_path(@link),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th>Username</th>
    <th>Password</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= user.username %></td>
    <td><%= user.password %></td>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Username:</b>
  <%= @user.username %>
</p>

<p>
  <b>Password:</b>
  <%= @user.password %>
</p>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>